---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '00:00'
    groups:
      github:
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: pip
    directory: '/.dagger-ci/daggerci'
    schedule:
      interval: 'daily'
      time: '00:00'
    groups:
      python:
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: gomod
    directory: '/action'
    schedule:
      interval: 'daily'
      time: '00:00'

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
