# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation
APPLY_FIXES: all
DISABLE:
  - COPYPASTE
DISABLE_LINTERS:
  - CSS_STYLELINT
  - GO_GOLANGCI_LINT
  - REPOSITORY_KICS
  - SPELL_LYCHEE
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
SHOW_ELAPSED_TIME: true

# Reporters
GITHUB_STATUS_REPORTER: true
FILEIO_REPORTER: false

# Python
PYTHON_PYLINT_CONFIG_FILE: .dagger-ci/daggerci/.pylintrc
PYTHON_FLAKE8_CONFIG_FILE: .dagger-ci/daggerci/.flake8
PYTHON_RUFF_CONFIG_FILE: .dagger-ci/daggerci/.ruff.toml

# Spelling
SPELL_CSPELL_ANALYZE_FILE_NAMES: false

# Trivy
REPOSITORY_TRIVY_CONFIG_FILE: .trivy.yaml

# yaml v8r
YAML_V8R_DISABLE_ERRORS: true

# markdown
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: (CHANGELOG\.md)
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true

# JAVASCRIPT_STANDARD
JAVASCRIPT_STANDARD_FILTER_REGEX_EXCLUDE: (pagetoc\.js)

# Bash shellcheck
BASH_SHELLCHECK_FILTER_REGEX_EXCLUDE: (shell-completion)
BASH_SHFMT_FILTER_REGEX_EXCLUDE: (shell-completion)
