---
name: 'Compile open firmware solution'
description: |
  Compile a selected firmware solution like coreboot, EDKII, OpenBMC and more
  The generated files will be placed in $GITHUB_WORKSPACE/build/
author: '9elements'
inputs:
  config:
    description: |
      Path to the JSON configuration file.
    required: true
  target:
    description: |
      The firmware recipe to build. Use ID from JSON configuration file.
    required: true
  recursive:
    description: |
      Build target recursively, with all of its dependencies.
    required: false
    default: 'false'

runs:
  using: 'node20'
  main: 'dist/invoke-action.mjs'
