[lint]
# Ignore things handled by pylint
# E501: Line too long
# LOG015: root logger call (using logging.<level>() directly is intentional here)
ignore = ["E501", "LOG015"]

[lint.per-file-ignores]
"test_filesystem.py" = ["F401"]
"test_orchestrator.py" = ["F401"]
