[book]
authors = ["AtomicFS"]
language = "en"
src = "src"
title = "firmware-action"
description = "Build system for firmware images for several open source firmware solutions"

[build]
build-dir = "public"
create-missing = false

[output.html]
mathjax-support = true
no-section-label = true
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/9elements/firmware-action"
git-repository-icon = "fab-git"
# icons: https://fontawesome.com/v4/icons/
smart-punctuation = false
admonitions = true

[output.html.fold]
enable = true
level = 2
