---
# Docs: https://github.com/agrc/reminder-action
#   create-reminder-action cannot be scheduled
#   for scheduled runs this is needed
name: 'reminder-schedule'

on:
  schedule:
    - cron: '0 0 * * *'
    # run daily

permissions:
  issues: write
  pull-requests: write

jobs:
  reminder-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: check reminders and notify
        uses: agrc/reminder-action@v1
