name: Docker test
on:
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  qemu-coreboot:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/9elements/coreboot:4.19
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Clone coreboot repository
        shell: bash
        run: |
          git clone --branch 4.19 --depth 1 https://review.coreboot.org/coreboot
      - name: Build coreboot for QEMU
        shell: bash
        working-directory: ./coreboot
        env:
          XGCCPATH: '/repo/coreboot/util/crossgcc/xgcc/bin/'
          BUILD_TIMELESS: 1
        run: |
          make clean
          make defconfig KBUILD_DEFCONFIG=../tests/coreboot-defconfig-qemu
          make -j "$(nproc)" || make
