---
# Example of using firmware-action

name: example
on:
  pull_request:
  pull_request_review:
    types: ['submitted']
  merge_group:
  push:
    branches: ['main']
    tags: ['v*']

env:
  APPLY_FIXES: none
  APPLY_FIXES_EVENT: pull_request
  APPLY_FIXES_MODE: commit
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # Status check for all jobs below
  # This is to allow SKIPPED be considered as SUCCESS
  status-check-example:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - build-uboot
      - build-uroot
      - test-operating-systems
    steps:
      - name: Check status
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: ${{ toJSON(needs) }}
          jobs: ${{ toJSON(needs) }}

  # Check we jobs should be ran or skipped
  skip-check:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changes:
              - '.github/workflows/example.yml'
              - 'docker/**'
              - 'tests/**'
              - 'action.yml'
              - 'cmd/firmware-action/**'

  # Change detection in action golang code
  changes:
    runs-on: ubuntu-latest
    needs: skip-check
    # Required permissions
    permissions:
      pull-requests: read
    outputs:
      compile: ${{ steps.compile.outputs.compile }}
    if: ${{ needs.skip-check.outputs.changes == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get latest release
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: ${{ github.ref }}
          noVersionBumpBehavior: patch
          noNewCommitBehavior: warn
      - name: Filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            action:
              - 'cmd/firmware-action/**'
      - name: Compile
        id: compile
        # Require compilation if changes in action golang code or if any breaking changes since last release
        run: |
          if [ "${{ steps.semver.outputs.bump }}" == "major" ] || [ "${{ steps.filter.outputs.action }}" == "true" ]; then
            echo "compile=true" >> "${GITHUB_OUTPUT}"
          else
            echo "compile=false" >> "${GITHUB_OUTPUT}"
          fi

  # Example of building u-root
  # ANCHOR: example_build_uroot
  build-uroot:
    needs:
      - changes
      - skip-check
    strategy:
      fail-fast: false
      matrix:
        uroot-version: ['0.14.0']
        arch: ['amd64', 'arm64']
    runs-on: ${{ matrix.arch == 'arm64' && 'ARM64' || 'ubuntu-latest' }}
    if: ${{ ! (github.event_name == 'pull_request_review' && github.actor != 'github-actions[bot]') && needs.skip-check.outputs.changes == 'true' }}
    # Skip if pull_request_review on PR not made by a bot
    steps:
      - name: Cleanup
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cached u-root repo
        uses: actions/cache/restore@v4
        id: cache-repo
        with:
          path: ./u-root
          key: u-root-${{ matrix.uroot-version }}-example
      - name: Clone u-root repo
        if: steps.cache-repo.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch v${{ matrix.uroot-version }} https://github.com/u-root/u-root.git || true
      - name: Store u-root repo in cache
        uses: actions/cache/save@v4
        if: steps.cache-repo.outputs.cache-hit != 'true'
        with:
          path: ./u-root
          key: u-root-${{ matrix.uroot-version }}-example

      - name: firmware-action
        uses: ./
        # uses: 9elements/firmware-action
        with:
          config: 'tests/example_config__uroot.json'
          target: 'u-root-example'
          recursive: 'false'
          compile: ${{ needs.changes.outputs.compile }}
        env:
          UROOT_VERSION: ${{ matrix.uroot-version }}
  # ANCHOR_END: example_build_uroot

  # Example of building u-boot
  # ANCHOR: example_build_uboot
  build-uboot:
    needs:
      - changes
      - skip-check
    strategy:
      fail-fast: false
      matrix:
        uboot-version: ['2025.01']
        arch: ['amd64', 'arm64']
    runs-on: ${{ matrix.arch == 'arm64' && 'ARM64' || 'ubuntu-latest' }}
    if: ${{ ! (github.event_name == 'pull_request_review' && github.actor != 'github-actions[bot]') && needs.skip-check.outputs.changes == 'true' }}
    # Skip if pull_request_review on PR not made by a bot
    steps:
      - name: Cleanup
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cached u-boot repo
        uses: actions/cache/restore@v4
        id: cache-repo
        with:
          path: ./u-boot
          key: u-boot-${{ matrix.uboot-version }}-example
      - name: Clone u-boot repo
        if: steps.cache-repo.outputs.cache-hit != 'true'
        run: |
          git clone https://source.denx.de/u-boot/u-boot.git
          cd u-boot
          git fetch -a
          git checkout "v${{ matrix.uboot-version }}"
      - name: Store u-boot repo in cache
        uses: actions/cache/save@v4
        if: steps.cache-repo.outputs.cache-hit != 'true'
        with:
          path: ./u-boot
          key: u-boot-${{ matrix.uboot-version }}-example

      - name: Move my defconfig into place (filename must not contain '.defconfig')
        run: |
          mv "tests/uboot_${{ matrix.uboot-version }}/uboot.defconfig" "uboot_defconfig"

      - name: firmware-action
        uses: ./
        # uses: 9elements/firmware-action
        with:
          config: 'tests/example_config__uboot.json'
          target: 'u-boot-example'
          recursive: 'false'
          compile: ${{ needs.changes.outputs.compile }}
        env:
          UBOOT_VERSION: ${{ matrix.uboot-version }}
  # ANCHOR_END: example_build_uboot

  # Example of running on non-Linux systems
  test-operating-systems:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        uroot-version: ['0.14.0']
    runs-on: ${{ matrix.os }}
    needs:
      - changes
      - skip-check
    if: ${{ ! (github.event_name == 'pull_request_review' && github.actor != 'github-actions[bot]') && needs.skip-check.outputs.changes == 'true' }}
    # Skip if pull_request_review on PR not made by a bot
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cached u-root repo
        uses: actions/cache/restore@v4
        id: cache-repo
        with:
          path: ./u-root
          key: u-root-${{ matrix.uroot-version }}-example
      - name: Clone u-root repo
        if: steps.cache-repo.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch v${{ matrix.uroot-version }} https://github.com/u-root/u-root.git
      - name: Store u-root repo in cache
        uses: actions/cache/save@v4
        if: steps.cache-repo.outputs.cache-hit != 'true'
        with:
          path: ./u-root
          key: u-root-${{ matrix.uroot-version }}-example

      - name: Install docker
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew install docker
          brew install colima
          brew services start colima

      - name: firmware-action
        continue-on-error: true
        # This one fails on Windows and MacOS
        # Since we do not have any real use-case right now, I will not fix it
        uses: ./
        with:
          config: 'tests/example_config.json'
          target: 'u-root-example'
          recursive: 'false'
          compile: ${{ needs.changes.outputs.compile }}
        env:
          COREBOOT_VERSION: '4.19'
          LINUX_VERSION: '6.9.9'
          SYSTEM_ARCH: 'amd64'
          EDK2_VERSION: 'edk2-stable202208'
          GCC_TOOLCHAIN_VERSION: 'GCC'
          UROOT_VERSION: ${{ matrix.uroot-version }}
