---
# Example of using firmware-action

name: example
on:
  pull_request:
  pull_request_review:
    types: ['submitted']
  merge_group:
  push:
    branches: ['main']
    tags: ['v*']
    paths:
      - '.github/workflows/example.yml'
      - 'docker/**'
      - 'tests/**'

env:
  APPLY_FIXES: none
  APPLY_FIXES_EVENT: pull_request
  APPLY_FIXES_MODE: commit
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # Example of building coreboot
  build-coreboot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coreboot-version: ['4.19', '4.20.1', '4.21', '24.02']
    if: ${{ ! (github.event_name == 'pull_request_review' && github.actor != 'github-actions[bot]') }}
    # Skip if pull_request_review on PR not made by a bot
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cached coreboot repo
        uses: actions/cache/restore@v4
        with:
          path: ./my_super_dooper_awesome_coreboot
          key: coreboot-${{ matrix.coreboot-version }}
      - name: Clone coreboot repo
        run: |
          git clone --branch "${{ matrix.coreboot-version }}" --depth 1 https://review.coreboot.org/coreboot my_super_dooper_awesome_coreboot || true
      - name: Store coreboot repo in cache
        uses: actions/cache/save@v4
        with:
          path: ./my_super_dooper_awesome_coreboot
          key: coreboot-${{ matrix.coreboot-version }}

      - name: Move my defconfig into place (filename must not contain '.defconfig')
        run: |
          mv "tests/coreboot_${{ matrix.coreboot-version }}/seabios.defconfig" "seabios_defconfig"
      - name: firmware-action
        uses: ./
        #uses: 9elements/firmware-action
        with:
          config: 'tests/example_config.json'
          target: 'coreboot-example'
          recursive: 'false'
        env:
          COREBOOT_VERSION: ${{ matrix.coreboot-version }}
      - name: Get artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coreboot-${{ matrix.coreboot-version }}
          path: output
          retention-days: 14

  # Example of building Linux kernel
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linux-version: [6.1.45]
    if: ${{ ! (github.event_name == 'pull_request_review' && github.actor != 'github-actions[bot]') }}
    # Skip if pull_request_review on PR not made by a bot
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cached linux source
        uses: actions/cache/restore@v4
        with:
          path: ./linux-${{ matrix.linux-version }}.tar.xz
          key: linux-${{ matrix.linux-version }}
      - name: Prepare linux kernel
        run: |
          # Download source files
          wget --quiet --continue "https://cdn.kernel.org/pub/linux/kernel/v${LINUX_MAJOR_VERSION}.x/linux-${{ matrix.linux-version }}.tar.xz"
          wget --quiet "https://cdn.kernel.org/pub/linux/kernel/v${LINUX_MAJOR_VERSION}.x/linux-${{ matrix.linux-version }}.tar.sign"
          unxz --keep "linux-${{ matrix.linux-version }}.tar.xz" >/dev/null
          # Verify GPG signature
          gpg2 --locate-keys torvalds@kernel.org gregkh@kernel.org
          gpg2 --verify "linux-${{ matrix.linux-version }}.tar.sign"
          # Extract
          tar -xvf "linux-${{ matrix.linux-version }}.tar"
        env:
          LINUX_MAJOR_VERSION: 6
      - name: Store linux source in cache
        uses: actions/cache/save@v4
        with:
          path: ./linux-${{ matrix.linux-version }}.tar.xz
          key: linux-${{ matrix.linux-version }}

      - name: Move my defconfig into place (filename must not contain '.defconfig')
        run: |
          mv "tests/linux_${{ matrix.linux-version }}/linux.defconfig" "ci_defconfig"
      - name: firmware-action
        uses: ./
        #uses: 9elements/firmware-action
        with:
          config: 'tests/example_config.json'
          target: 'linux-example'
          recursive: 'false'
        env:
          LINUX_VERSION: ${{ matrix.linux-version }}
      - name: Get artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.linux-version }}
          path: output
          retention-days: 14

  # Example of building EDK2
  build-edk2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        edk2-version: ['edk2-stable202208', 'edk2-stable202211']
    if: ${{ ! (github.event_name == 'pull_request_review' && github.actor != 'github-actions[bot]') }}
    # Skip if pull_request_review on PR not made by a bot
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cached edk2 repo
        uses: actions/cache/restore@v4
        with:
          path: ./Edk2
          key: edk2-${{ matrix.edk2-version }}
      - name: Clone edk2 repo
        run: |
          git clone --recurse-submodules --branch "${{ matrix.edk2-version }}" --depth 1 https://github.com/tianocore/edk2.git Edk2 || true
      - name: Prepare file with build arguments
        run: |
          echo "-D BOOTLOADER=COREBOOT -D TPM_ENABLE=TRUE -D NETWORK_IPXE=TRUE" > "edk2_config.cfg"
      - name: Store edk2 repo in cache
        uses: actions/cache/save@v4
        with:
          path: ./Edk2
          key: edk2-${{ matrix.edk2-version }}

      - name: firmware-action
        uses: ./
        #uses: 9elements/firmware-action
        with:
          config: 'tests/example_config.json'
          target: 'edk2-example'
          recursive: 'false'
        env:
          EDK2_VERSION: ${{ matrix.edk2-version }}
      - name: Get artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.edk2-version }}
          path: output
          retention-days: 14

  # Example of building Firmware Stitching
  build-stitching:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coreboot-version: ['4.19']
    if: ${{ ! (github.event_name == 'pull_request_review' && github.actor != 'github-actions[bot]') }}
    # Skip if pull_request_review on PR not made by a bot
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cached coreboot-blobs repo
        uses: actions/cache/restore@v4
        with:
          path: ./stitch
          key: coreboot-blobs-${{ matrix.coreboot-version }}
      - name: Clone blobs repo
        run: |
          git clone --depth 1 https://review.coreboot.org/blobs stitch || true
      - name: Store coreboot-blobs repo in cache
        uses: actions/cache/save@v4
        with:
          path: ./stitch
          key: coreboot-blobs-${{ matrix.coreboot-version }}

      - name: firmware-action
        uses: ./
        #uses: 9elements/firmware-action
        with:
          config: 'tests/example_config.json'
          target: 'stitching-example'
          recursive: 'false'
        env:
          COREBOOT_VERSION: ${{ matrix.coreboot-version }}
      - name: Get artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.coreboot-version }}
          path: output
          retention-days: 14

  # Example of building u-root
  build-uroot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        uroot-version: ['0.14.0']
    if: ${{ ! (github.event_name == 'pull_request_review' && github.actor != 'github-actions[bot]') }}
    # Skip if pull_request_review on PR not made by a bot
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cached u-root repo
        uses: actions/cache/restore@v4
        with:
          path: ./u-root
          key: u-root-${{ matrix.uroot-version }}
      - name: Clone u-root repo
        run: |
          git clone --depth 1 --branch v${{ matrix.uroot-version }} https://github.com/u-root/u-root.git || true
      - name: Store u-root repo in cache
        uses: actions/cache/save@v4
        with:
          path: ./u-root
          key: u-root-${{ matrix.uroot-version }}

      - name: firmware-action
        uses: ./
        #uses: 9elements/firmware-action
        with:
          config: 'tests/example_config.json'
          target: 'u-root-example'
          recursive: 'false'
        env:
          UROOT_VERSION: ${{ matrix.uroot-version }}
      - name: Get artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.uroot-version }}
          path: output
          retention-days: 14

  # Example of running on non-Linux systems
  test-operating-systems:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        uroot-version: ['0.14.0']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cached u-root repo
        uses: actions/cache/restore@v4
        with:
          path: ./u-root
          key: u-root-${{ matrix.uroot-version }}
      - name: Clone u-root repo
        run: |
          git clone --depth 1 --branch v${{ matrix.uroot-version }} https://github.com/u-root/u-root.git || true
      - name: Store u-root repo in cache
        uses: actions/cache/save@v4
        with:
          path: ./u-root
          key: u-root-${{ matrix.uroot-version }}

      - name: Install docker
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew install docker
          brew install colima
          brew services start colima

      - name: firmware-action
        continue-on-error: true
        # This one fails on Windows and MacOS
        # Since we do not have any real use-case right now, I will not fix it
        uses: ./
        with:
          config: 'tests/example_config.json'
          target: 'u-root-example'
          recursive: 'false'
        env:
          UROOT_VERSION: ${{ matrix.uroot-version }}
