---
# Test built docker images by building simple projects inside them

name: go-test
on:
  pull_request:
    paths:
      - '.github/workflows/go-test.yml'
      - 'action/**'
  pull_request_review:
    types: ['submitted']
  merge_group:
  push:
    branches: ['main']
    tags: ['v*']
    paths:
      - '.github/workflows/go-test.yml'
      - 'action/**'

permissions:
  contents: read

jobs:
  # Status check for all jobs below
  # This is to allow SKIPPED be considered as SUCCESS
  status-check-go-test:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - go-test-resource-hogs
      - go-test
    steps:
      - name: Check status
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: ${{ toJSON(needs) }}
          jobs: ${{ toJSON(needs) }}

  go-test-resource-hogs:
    # Run tests that take up a lot of system resources separately
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testregex: ['TestLinux', 'TestEdk2', 'TestCoreboot', 'TestStitching', 'TestURoot']
    if: ${{ ! (github.event_name == 'pull_request_review' && github.actor != 'github-actions[bot]') }}
    # Skip if pull_request_review on PR not made by a bot
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install Taskfile
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
      - name: Install go dependencies
        run: |
          cd action
          go get -d ./...
      - name: Run go test
        run: |
          cd action
          go test -race -v -timeout 60m -shuffle=on -covermode=atomic -coverprofile coverage.out -run ${{ matrix.testregex }} ./...

  go-test:
    # Run all remaining light tests
    runs-on: ubuntu-latest
    if: ${{ ! (github.event_name == 'pull_request_review' && github.actor != 'github-actions[bot]') }}
    # Skip if pull_request_review on PR not made by a bot
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install Taskfile
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
      - name: Install go dependencies
        run: |
          cd action
          go get -d ./...
      - name: Run go test
        run: |
          cd action
          go test -race -v -timeout 60m -shuffle=on -covermode=atomic -coverprofile coverage.out -skip '(TestLinux|TestEdk2|TestCoreboot|TestStitching)' ./...
