---
# Test built docker images by building simple projects inside them

name: go test
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Taskfile
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
      - name: Install go dependencies
        run: |
          cd action
          go get -d ./...
      - name: Run go test
        run: ./bin/task test
