---
# Test built docker images by building simple projects inside them

name: pytest
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install deps
        run: |
          curl -SL "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
          sudo mv docker-compose /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          docker-compose -f docker/compose.yaml config
      - name: Install python dependencies
        run: pip install -r ./.dagger-ci/daggerci/requirements.txt
      - name: Run pytest
        run: .dagger-ci/run_pytest.sh
