---
# Test built docker images by building simple projects inside them

name: pytest
on:
  pull_request:
    paths:
      - '.dagger-ci/**'
      - '.github/workflows/pytest.yml'
  pull_request_review:
    types: ['submitted']
  merge_group:
  push:
    branches: ['main']
    tags: ['v*']
    paths:
      - '.dagger-ci/**'
      - '.github/workflows/pytest.yml'

permissions:
  contents: read

jobs:
  # Status check for all jobs below
  # This is to allow SKIPPED be considered as SUCCESS
  status-check-pytest:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - pytest
    steps:
      - name: Check status
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: ${{ toJSON(needs) }}
          jobs: ${{ toJSON(needs) }}

  pytest:
    runs-on: ubuntu-latest
    if: ${{ ! (github.event_name == 'pull_request_review' && github.actor != 'github-actions[bot]') }}
    # Skip if pull_request_review on PR not made by a bot
    steps:
      - name: Install Taskfile
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: |
          curl -SL "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
          sudo mv docker-compose /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          docker-compose -f docker/compose.yaml config
      - name: Install python dependencies
        run: pip install -r ./.dagger-ci/daggerci/requirements.txt
      - name: Run pytest
        run: |
          cd .dagger-ci
          task test
