---
# Run scheduled renovatebot

name: renovate
on:
  schedule:
    # Run daily at midnight
    - cron: '0 0 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40
        with:
          configurationFile: .renovate.js
          token: ${{ secrets.RENOVATE_TOKEN }}
